name: ClojureScript Test
on: [push]

jobs:
  cljs-test:
    name: ClojureScript Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          tools-deps: '1.12.0.1479'

      - name: Cache maven
        uses: actions/cache@v4
        env:
          cache-name: cache-maven
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cache gitlibs
        uses: actions/cache@v4
        env:
          cache-name: cache-gitlibs
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Run tests
        run: clojure -M:test:cljs-runner
